import type { LucideIcon, LucideProps } from "lucide-react"
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Building,
  Building2,
  CalendarDays,
  ChevronDown,
  Clock,
  Diamond,
  Droplet,
  Dumbbell,
  Download,
  FilePen,
  Facebook,
  Flame,
  Flower,
  FolderArchive,
  FolderOpen,
  Gavel,
  Hand,
  Hotel,
  Images,
  Instagram,
  Luggage,
  Mail,
  Map,
  MapPin,
  Menu,
  Music2,
  Mountain,
  Newspaper,
  PartyPopper,
  Phone,
  Play,
  PlayCircle,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Sparkles,
  Star,
  Stars,
  Theater,
  Youtube,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  badge: BadgeCheck,
  calendar_month: CalendarDays,
  celebration: PartyPopper,
  checkroom: Shirt,
  diamond: Diamond,
  edit_document: FilePen,
  expand_more: ChevronDown,
  facebook: Facebook,
  fitness_center: Dumbbell,
  folder_open: FolderOpen,
  folder_zip: FolderArchive,
  gavel: Gavel,
  hotel: Hotel,
  instagram: Instagram,
  local_fire_department: Flame,
  local_mall: ShoppingBag,
  location_city: Building2,
  location_on: MapPin,
  luggage: Luggage,
  mail: Mail,
  map: Map,
  menu: Menu,
  music_note: Music2,
  newsmode: Newspaper,
  phone: Phone,
  photo_library: Images,
  play_arrow: Play,
  play_circle: PlayCircle,
  policy: ShieldCheck,
  schedule: Clock,
  spa: Flower,
  star: Star,
  stars: Stars,
  terrain: Mountain,
  theater_comedy: Theater,
  youtube: Youtube,
  verified: BadgeCheck,
  waving_hand: Hand,
  water_drop: Droplet,
  apartment: Building,
  download: Download,
}

type IconProps = {
  name: string
} & LucideProps

export function Icon({ name, ...props }: IconProps) {
  const LucideIcon = iconMap[name] ?? Sparkles
  return <LucideIcon aria-hidden="true" {...props} />
}
